version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres_practice
    build: ./image/postgres
    ports: 
      - "15432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER:=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    container_name: django_practice
    command: >
        python manage.py runserver 0.0.0.0:8000;
        apt update && apt install vim
    volumes:
      - .:/code
    ports:
      - "18000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

